const K="target-list-v2",ID=()=>crypto.randomUUID(),CURRENCY={USD:{s:"$",x:""},EUR:{s:"€",x:""},JPY:{s:"¥",x:""},GBP:{s:"£",x:""},AUD:{s:"$",x:" AUD"},CAD:{s:"$",x:" CAD"},CHF:{s:"CHF ",x:""}};
let S=JSON.parse(localStorage.getItem(K)||"null")||{lists:[{id:ID(),name:"My Target Run",budget:0,items:[]}],current:null,filter:"all",cat:"All",defaultCat:"Grocery",currency:"USD",favorites:[]};
S.current=S.current||S.lists[0].id;S.currency=S.currency||"USD";S.favorites=S.favorites||[];
// V2.4 migration: favorites are now standalone records. Existing item-level favorites become linked records.
const legacyFavs=[];
S.lists.forEach(l=>l.items.forEach(x=>{
  x.qty??=1;x.price??=0;x.cat??=S.defaultCat||"Grocery";x.aisle??="";x.note??="";x.done??=false;
  if(x.fav===true&&!x.favoriteId){
    const key=x.name.trim().toLowerCase();
    let f=S.favorites.find(f=>f.name.trim().toLowerCase()===key);
    if(!f){f={id:ID(),name:x.name,cat:x.cat,price:x.price,aisle:x.aisle,note:x.note};S.favorites.push(f)}
    x.favoriteId=f.id;
  }
  delete x.fav;
}));
const favoriteById=id=>S.favorites.find(f=>f.id===id);
const favoriteListNames=id=>S.lists.filter(l=>l.items.some(x=>x.favoriteId===id)).map(l=>l.name);
let eid=null,favId=null,menuId=null,deleteId=null,shoppingFilter="all",deleteFavoriteId=null;const $=x=>document.querySelector(x),cur=()=>S.lists.find(x=>x.id===S.current),save=()=>localStorage.setItem(K,JSON.stringify(S));
const money=n=>{let c=CURRENCY[S.currency]||CURRENCY.USD,v=Number(n||0);return c.s+(S.currency==="JPY"?Math.round(v):v.toFixed(2))+c.x};
const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const total=l=>l.items.reduce((n,x)=>n+Number(x.price||0)*Number(x.qty||1),0);const budget=l=>({t:total(l),b:Number(l.budget||0),left:Number(l.budget||0)-total(l)});
const targetButton=n=>`<button class="target-btn" data-t="${esc(n)}"><span class="target-logo"></span><span>Target</span></button>`;
const starStatus=x=>`<span class="star status-star" aria-label="${x.favoriteId?"Favorite":"Not a favorite"}" title="${x.favoriteId?"Favorite":"Not a favorite"}">${x.favoriteId?"★":"☆"}</span>`;
function add(n){n=n.trim();if(!n)return;cur().items.push({id:ID(),name:n,cat:S.defaultCat,qty:1,price:0,aisle:"",note:"",done:false});save();render()}
function render(){let l=cur();if(!l)return;$("#listName").value=l.name;let a=l.items.filter(x=>(S.filter==="all"||(S.filter==="open"&&!x.done)||(S.filter==="done"&&x.done))&&(S.cat==="All"||x.cat===S.cat));$("#items").innerHTML=a.map(x=>`<div class="item ${x.done?"done":""}"><button class="check" data-c="${x.id}">${x.done?"✓":""}</button><button class="item-main" data-e="${x.id}"><span class="name">${esc(x.name)}</span><span class="meta">${esc(x.cat)}${x.aisle?" · "+esc(x.aisle):""}${x.note?" · "+esc(x.note):""}${x.price?" · "+money(x.price*x.qty):""}</span></button><div class="qty-control"><button class="qty-btn" data-q="${x.id}" data-d="-1">−</button><span class="qty-value">${x.qty}</span><button class="qty-btn" data-q="${x.id}" data-d="1">+</button></div>${starStatus(x)}${targetButton(x.name)}<button class="item-delete" data-di="${x.id}" aria-label="Delete item">×</button></div>`).join("");
a.forEach(x=>{$(`[data-c="${x.id}"]`).onclick=()=>{x.done=!x.done;save();render()};$(`[data-e="${x.id}"]`).onclick=()=>edit(x.id);document.querySelectorAll(`[data-q="${x.id}"]`).forEach(b=>b.onclick=()=>{x.qty=Math.max(1,x.qty+Number(b.dataset.d));save();render()});$(`[data-di="${x.id}"]`).onclick=()=>{cur().items=cur().items.filter(i=>i.id!==x.id);save();render()}});document.querySelectorAll("[data-t]").forEach(b=>b.onclick=()=>open("https://www.target.com/s?searchTerm="+encodeURIComponent(b.dataset.t),"_blank"));
let done=l.items.filter(x=>x.done).length,b=budget(l);$("#stats").textContent=`${done} of ${l.items.length} items · ${money(b.t)}`;$("#bar").style.width=l.items.length?done/l.items.length*100+"%":"0%";$("#budget").value=l.budget||"";$("#bt").textContent=`${money(b.t)} / ${money(b.b)}`;$("#left").textContent=b.b?`${money(Math.abs(b.left))} ${b.left<0?"over budget":"left"}`:"";$("#bt").classList.toggle("over-budget",b.left<0);$("#left").classList.toggle("over-budget",b.left<0);$("#bb").style.width=b.b?Math.min(100,b.t/b.b*100)+"%":"0%";lists();favs();renderShopping()}
function showDialog(id){const d=$(id);document.activeElement?.blur();d.showModal();requestAnimationFrame(()=>d.focus({preventScroll:true}))}
function edit(i){eid=i;let x=cur().items.find(a=>a.id===i);$("#en").value=x.name;$("#ec").value=x.cat;$("#eq").value=x.qty;$("#ep").value=x.price;$("#ea").value=x.aisle;$("#note").value=x.note;$("#editFavoriteStar").textContent=x.favoriteId?"★":"☆";$("#editFavoriteStar").classList.toggle("active",!!x.favoriteId);showDialog("#edit")}
function lists(){$("#listCards").innerHTML=S.lists.map(l=>`<div class="listcard"><button class="list-name" data-o="${l.id}"><b>${esc(l.name)}</b><span class="meta">${l.items.filter(x=>!x.done).length} open · ${l.items.length} total</span></button><button class="list-menu" data-m="${l.id}">•••</button></div>`).join("");document.querySelectorAll("[data-o]").forEach(b=>b.onclick=()=>{S.current=b.dataset.o;S.filter="all";S.cat="All";save();view("shop");render()});document.querySelectorAll("[data-m]").forEach(b=>b.onclick=()=>openMenu(b.dataset.m))}
function openMenu(id){menuId=id;$("#listMenuTitle").textContent=S.lists.find(x=>x.id===id).name;showDialog("#listMenu")}
function duplicate(id){let l=S.lists.find(x=>x.id===id),c={id:ID(),name:l.name+" Copy",budget:l.budget,items:l.items.map(x=>({...x,id:ID(),done:false}))};S.lists.push(c);S.current=c.id;save();render()}
function askDelete(id){if(S.lists.length<=1){alert("You must keep at least one list.");return}deleteId=id;$("#confirmListName").textContent=S.lists.find(x=>x.id===id).name;showDialog("#confirmDelete")}
function delList(id){if(S.lists.length<=1)return;let i=S.lists.findIndex(x=>x.id===id);S.lists.splice(i,1);if(S.current===id)S.current=S.lists[Math.max(0,i-1)].id;save();view("lists");render()}
function rename(id){let l=S.lists.find(x=>x.id===id),n=prompt("List name",l.name);if(n&&n.trim()){l.name=n.trim();save();render()}}
function favs(){
  $("#favCards").innerHTML=S.favorites.length?S.favorites.map(f=>{let names=favoriteListNames(f.id);return `<div class="favorite-card"><div class="favorite-info"><b>${esc(f.name)}</b><span class="meta">${esc(f.cat)}${f.price?" · "+money(f.price):""}</span><span class="favorite-lists"><strong>Lists:</strong> ${names.length?names.map(esc).join(", "):"None"}</span></div>${targetButton(f.name)}<button class="edit-fav" data-fe="${f.id}">Edit</button></div>`}).join(""):"<div class='card muted'>No favorites yet.<br>Use Add Favorite on this tab to create one.</div>";
  document.querySelectorAll("[data-fe]").forEach(b=>b.onclick=()=>editFav(b.dataset.fe));document.querySelectorAll("#favCards [data-t]").forEach(b=>b.onclick=()=>open("https://www.target.com/s?searchTerm="+encodeURIComponent(b.dataset.t),"_blank"))
}
function editFav(id=null){favId=id;let f=id?favoriteById(id):null;$("#favoriteEditTitle").textContent=id?"Edit Favorite":"Add Favorite";$("#fn").value=f?.name||"";$("#fc").value=f?.cat||S.defaultCat;$("#fp").value=f?.price||0;$("#fa").value=f?.aisle||"";$("#fnote").value=f?.note||"";$("#deleteFavorite").classList.toggle("hidden",!id);showDialog("#favoriteEdit")}
function addFavoriteToCurrent(id){let f=favoriteById(id);if(!f)return;let x=cur().items.find(x=>x.favoriteId===id)||cur().items.find(x=>x.name.toLowerCase()===f.name.toLowerCase());if(x){x.favoriteId=id;x.name=f.name}else{cur().items.push({id:ID(),name:f.name,cat:f.cat,qty:1,price:f.price||0,aisle:f.aisle||"",note:f.note||"",done:false,favoriteId:id})}save();$("#favoritePicker").close();render()}
function picker(){let n=S.favorites;$("#favoriteTargetList").textContent=cur().name;$("#favoritePickerList").innerHTML=n.length?n.map(f=>`<button class="picker-favorite" data-pick="${f.id}"><span>★</span><b>${esc(f.name)}</b><small>${favoriteListNames(f.id).length?favoriteListNames(f.id).map(esc).join(", "):"Not on this list"}</small></button>`).join(""):"<div class='muted picker-empty'>No favorites exist yet. Create one from the Favorites tab.</div>";document.querySelectorAll("[data-pick]").forEach(b=>b.onclick=()=>addFavoriteToCurrent(b.dataset.pick))}
function updateFav(id,d){let f=favoriteById(id);if(!f)return;let oldName=f.name;Object.assign(f,d);S.lists.forEach(l=>l.items.forEach(x=>{if(x.favoriteId===id)Object.assign(x,{name:f.name,cat:f.cat,price:f.price,aisle:f.aisle,note:f.note})}));}
function deleteFavorite(id){S.favorites=S.favorites.filter(f=>f.id!==id);S.lists.forEach(l=>l.items.forEach(x=>{if(x.favoriteId===id)delete x.favoriteId}));}
function confirmDeleteFavorite(id){let f=favoriteById(id);if(!f)return;let names=favoriteListNames(id);if(names.length){deleteFavoriteId=id;$("#confirmFavoriteName").textContent=f.name;$("#confirmFavoriteLists").textContent=names.join(", ");showDialog("#confirmFavoriteDelete")}else{deleteFavorite(id);save();render();}}
function renderShopping(){let l=cur(),b=budget(l),done=l.items.filter(x=>x.done).length;$("#shoppingTitle").textContent=l.name;$("#shoppingProgress").textContent=`${done} of ${l.items.length} items complete`;$("#shoppingTotal").textContent=money(b.t)+" estimated";$("#shoppingBudgetValue").textContent=`${money(b.t)} / ${money(b.b)}`;$("#shoppingBudgetLeft").textContent=b.b?`${money(Math.abs(b.left))} ${b.left<0?"over budget":"left"}`:"";$("#shoppingBudgetValue").classList.toggle("over-budget",b.left<0);$("#shoppingBudgetLeft").classList.toggle("over-budget",b.left<0);let a=l.items.filter(x=>shoppingFilter==="all"||(shoppingFilter==="open"&&!x.done)||(shoppingFilter==="done"&&x.done));$("#shoppingItems").innerHTML=a.length?a.map(x=>`<div class="shopping-item ${x.done?"done":""}"><button class="shopping-check" data-sc="${x.id}">${x.done?"✓":""}</button><div class="shopping-main"><button class="shopping-name" data-se="${x.id}">${esc(x.name)}</button><div class="shopping-meta">${esc(x.cat)}${x.aisle?" · "+esc(x.aisle):""} · ${money(x.price*x.qty)}</div>${x.note?`<div class="shopping-note">📝 ${esc(x.note)}</div>`:""}</div><div class="qty-control"><button class="qty-btn" data-sq="${x.id}" data-d="-1">−</button><span class="qty-value">${x.qty}</span><button class="qty-btn" data-sq="${x.id}" data-d="1">+</button></div>${starStatus(x)}${targetButton(x.name)}</div>`).join(""):"<div class='card muted'>No items match this filter.</div>";document.querySelectorAll("[data-sc]").forEach(b=>b.onclick=()=>{let x=cur().items.find(a=>a.id===b.dataset.sc);x.done=!x.done;save();render()});document.querySelectorAll("[data-se]").forEach(b=>b.onclick=()=>edit(b.dataset.se));document.querySelectorAll("[data-sq]").forEach(b=>b.onclick=()=>{let x=cur().items.find(a=>a.id===b.dataset.sq);x.qty=Math.max(1,x.qty+Number(b.dataset.d));save();render()});document.querySelectorAll("#shoppingItems [data-t]").forEach(b=>b.onclick=()=>open("https://www.target.com/s?searchTerm="+encodeURIComponent(b.dataset.t),"_blank"))}
function view(v){document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$("#"+v).classList.remove("hidden");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.v===v))}
$("#add").onclick=()=>{add($("#item").value);$("#item").value=""};$("#item").onkeydown=e=>{if(e.key==="Enter")$("#add").click()};document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{view(b.dataset.v);render()});document.querySelectorAll(".f").forEach(b=>b.onclick=()=>{S.filter=b.dataset.f;document.querySelectorAll(".f").forEach(x=>x.classList.remove("active"));b.classList.add("active");render()});document.querySelectorAll(".sf").forEach(b=>b.onclick=()=>{shoppingFilter=b.dataset.sf;document.querySelectorAll(".sf").forEach(x=>x.classList.toggle("active",x===b));renderShopping()});$("#cat").onchange=e=>{S.cat=e.target.value;render()};$("#listName").onchange=e=>{cur().name=e.target.value||"My Target Run";save();render()};$("#budget").onchange=e=>{cur().budget=Number(e.target.value)||0;save();render()};$("#clear").onclick=()=>{cur().items=cur().items.filter(x=>!x.done);save();render()};
$("#share").onclick=async()=>{let t=cur().name+"\n"+cur().items.map(x=>`${x.done?"☑":"☐"} ${x.name} ×${x.qty}`).join("\n");if(navigator.share)await navigator.share({title:cur().name,text:t});else if(navigator.clipboard)await navigator.clipboard.writeText(t)};
function createList(){let n=prompt("New list name","Weekly Target Run");if(n){S.lists.push({id:ID(),name:n,budget:0,items:[]});S.current=S.lists.at(-1).id;save();render()}}$("#newList").onclick=createList;$("#newListFromLists").onclick=createList;$("#duplicateCurrent").onclick=()=>duplicate(S.current);$("#deleteCurrent").onclick=()=>askDelete(S.current);$("#mode").onclick=()=>{shoppingFilter="all";document.querySelectorAll(".sf").forEach(x=>x.classList.toggle("active",x.dataset.sf==="all"));view("shoppingMode");renderShopping()};$("#exitMode").onclick=()=>{view("shop");render()};
$("#addFavorite").onclick=()=>{picker();showDialog("#favoritePicker")};$("#createFavorite").onclick=()=>editFav();$("#saveFavorite").onclick=()=>{let d={name:$("#fn").value.trim(),cat:$("#fc").value,price:Math.max(0,Number($("#fp").value)||0),aisle:$("#fa").value.trim(),note:$("#fnote").value.trim()};if(!d.name)return;if(favId)updateFav(favId,d);else if(S.favorites.some(f=>f.name.toLowerCase()===d.name.toLowerCase())){alert("A favorite with that name already exists.");return}else S.favorites.push({id:ID(),...d});$("#favoriteEdit").close();favId=null;save();render()};
$("#menuEdit").onclick=()=>{let id=menuId;$("#listMenu").close();rename(id)};$("#menuDuplicate").onclick=()=>{let id=menuId;$("#listMenu").close();duplicate(id)};$("#menuDelete").onclick=()=>{let id=menuId;$("#listMenu").close();askDelete(id)};$("#confirmDeleteButton").onclick=()=>{let id=deleteId;deleteId=null;delList(id)};
$("#save").onclick=()=>{let x=cur().items.find(a=>a.id===eid);Object.assign(x,{name:$("#en").value.trim()||x.name,cat:$("#ec").value,qty:Math.max(1,Number($("#eq").value)||1),price:Math.max(0,Number($("#ep").value)||0),aisle:$("#ea").value.trim(),note:$("#note").value.trim()});save();render()};$("#del").onclick=()=>{cur().items=cur().items.filter(x=>x.id!==eid);save();render()};
$("#deleteFavorite").onclick=()=>{let id=favId;$("#favoriteEdit").close();favId=null;if(id)confirmDeleteFavorite(id)};
$("#confirmFavoriteDeleteButton").onclick=()=>{let id=deleteFavoriteId;deleteFavoriteId=null;$("#confirmFavoriteDelete").close();if(id)deleteFavorite(id);save();render()};
$("#defaultCat").value=S.defaultCat;$("#defaultCat").onchange=e=>{S.defaultCat=e.target.value;save()};$("#currency").value=S.currency;$("#currency").onchange=e=>{S.currency=e.target.value;save();render()};$("#reset").onclick=()=>{if(confirm("Reset all app data?")){localStorage.removeItem(K);location.reload()}};if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");save();render();
